// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examination_system.Models;

[PrimaryKey("QuestionId", "Choice1")]
[Table("Choice")]
public partial class Choice
{
    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Key]
    [Column("Choice")]
    [StringLength(100)]
    [Unicode(false)]
    public string Choice1 { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Choices")]
    public virtual Question Question { get; set; }
}