// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examination_system.Models;

[PrimaryKey("CourseId", "StudentId")]
[Table("Enrollment")]
public partial class Enrollment
{
    [Key]
    [Column("Course_Id")]
    public int CourseId { get; set; }

    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Grade { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Enrollments")]
    public virtual Course Course { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("Enrollments")]
    public virtual Student Student { get; set; }
}