// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examination_system.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    public DateOnly Date { get; set; }

    [Column("Course_Id")]
    public int CourseId { get; set; }

    [Column("Instructor_Id")]
    public int InstructorId { get; set; }

    [Column("MCQ_Grade", TypeName = "decimal(5, 2)")]
    public decimal McqGrade { get; set; }

    [Column("TF_Grade", TypeName = "decimal(5, 2)")]
    public decimal TfGrade { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    [ForeignKey("InstructorId")]
    [InverseProperty("Exams")]
    public virtual Instructor Instructor { get; set; }
}