// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class GetInstructorResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string Degree { get; set; }
        public string Address { get; set; }
        [Column("Hour_Rate", TypeName = "decimal(18,0)")]
        public decimal? Hour_Rate { get; set; }
        [Column("Salary", TypeName = "decimal(18,0)")]
        public decimal? Salary { get; set; }
        [Column("Bonus", TypeName = "decimal(18,0)")]
        public decimal? Bonus { get; set; }
        public int? Department_Id { get; set; }
    }
}
