// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examination_system.Models;

[Table("Instructor")]
public partial class Instructor
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [MaxLength(255)]
    public byte[] Password { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Degree { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("Hour_Rate", TypeName = "decimal(18, 0)")]
    public decimal? HourRate { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? Salary { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? Bonus { get; set; }

    [Column("Department_Id")]
    public int? DepartmentId { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Instructors")]
    public virtual Department Department { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [InverseProperty("Instructor")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [ForeignKey("InstructorId")]
    [InverseProperty("Instructors")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}