// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class Select_TopicResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Course_Id { get; set; }
    }
}
