// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class SelectEnrollmentResult
    {
        public int Course_Id { get; set; }
        public int Student_Id { get; set; }
        [Column("Grade", TypeName = "decimal(18,2)")]
        public decimal? Grade { get; set; }
    }
}
