// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class SelectExamResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateOnly Date { get; set; }
        public int Course_Id { get; set; }
        public int Instructor_Id { get; set; }
        [Column("MCQ_Grade", TypeName = "decimal(5,2)")]
        public decimal MCQ_Grade { get; set; }
        [Column("TF_Grade", TypeName = "decimal(5,2)")]
        public decimal TF_Grade { get; set; }
    }
}
