// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class Select_StudentAnswerResult
    {
        public int Student_Id { get; set; }
        public int Exam_Id { get; set; }
        public int Question_Id { get; set; }
        public string Choice { get; set; }
        [Column("Grade", TypeName = "decimal(5,2)")]
        public decimal? Grade { get; set; }
    }
}
