// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class SP_ReportingGetExamQuestionsResult
    {
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public string ChoiceText { get; set; }
    }
}
