// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examination_system.Models
{
    public partial class SP_rExamQuestionsResult
    {
        public int Question_Id { get; set; }
        public int Question_Order { get; set; }
    }
}
