// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examination_system.Models;

[PrimaryKey("StudentId", "ExamId", "QuestionId")]
[Table("StudentAnswer")]
public partial class StudentAnswer
{
    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [Key]
    [Column("Exam_Id")]
    public int ExamId { get; set; }

    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Choice { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Grade { get; set; }

    [ForeignKey("ExamId, QuestionId")]
    [InverseProperty("StudentAnswers")]
    public virtual ExamQuestion ExamQuestion { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentAnswers")]
    public virtual Student Student { get; set; }
}